name: lint-and-test-ci-app

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
   
      - uses: actions/checkout@v2
        with:
          node-version: 14
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: make setup
      - run: make lint
      - name: run test
        run: make test

      - name: snyk check code
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: -- all-projects

     
        
